language: node_js
node_js:
  - node
notifications:
  email:
    recipients:
      - marc.marina.miravitlles@gmail.com

    on_success: change
    on_failure: always

script:
  - yarn install
  - yarn seed
  - yarn test

services: mongodb

before_script:
  - sleep 15

git:
  depth: false
