version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  unit-testing: 
    docker:       
      - image: node:15-alpine3.10        
    steps:
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: cp package.json ./       
      - run: cp yarn.lock ./       
      - run: yarn
      - run: cp -r src ./src
      - run: yarn test

workflows:
  testing:
    jobs:
      - unit-testing:
        filters: 
          branches:
            only: /*/
          