version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  test: 
    docker:       
      - image: node-14:latest        
    steps:       
      - run: echo "hello world"  
     

workflows:
  testing:
    jobs:
      - test:
        filters: 
          branches:
            only: /*/  
          