version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  unit-testing: 
    docker:       
      - image: node:15-alpine3.10        
    steps:       
      - run: yarn
      - run: yarn test

workflows:
  testing:
    jobs:
      - unit-testing:
        filters: 
          branches:
            only: /*/
  matrix-tests:
    jobs:
      - node/test:
          version: 13.11.0
      - node/test:
          version: 12.16.0
      - node/test:
          version: 10.19.0
          