version: 2.1
orbs:
  node: circleci/node@5.0.3

jobs:
  test:
    docker:
      - image: cimg/node:16.18.1
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test --maxWorkers=2
  build:
    docker:
      - image: cimg/node:16.18.1
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn build
  stage:
    docker:
      - image: cimg/node:16.18.1
    steps:
      - checkout
      - run: cd scripts && yarn install --frozen-lockfile
      - run: node scripts/deploy.js $DEPLOY_WEBHOOK_URL_STAGING
  deploy:
    docker:
      - image: cimg/node:16.18.1
    steps:
      - checkout
      - run: cd scripts && yarn install --frozen-lockfile
      - run: node scripts/deploy.js $DEPLOY_WEBHOOK_URL

workflows:
  pipeline:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: develop
      - stage:
          requires:
            - test
            - build
          filters:
            branches:
              only: develop
