version: 2.1
orbs:
  node: circleci/node@5.1.0
commands:
  checkout-and-install:
    steps:
      - checkout
      - run: yarn install --frozen-lockfile

jobs:
  test:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout-and-install
      - run: yarn build
      - run: yarn run test --runInBand
  build:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout-and-install
      - run: yarn build
  stage:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout-and-install
      - run: yarn build
      - run: yarn run deploy $DEPLOY_WEBHOOK_URL_STAGING
  deploy:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout-and-install
      - run: yarn build
      - run: yarn run deploy $DEPLOY_WEBHOOK_URL

workflows:
  pipeline:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: develop
      - stage:
          requires:
            - test
            - build
          filters:
            branches:
              only: develop
