version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test
  stage:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: cd scripts && yarn install --frozen-lockfile
      - run: node scripts/deploy.js $DEPLOY_WEBHOOK_URL_STAGING
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: cd scripts && yarn install --frozen-lockfile
      - run: node scripts/deploy.js $DEPLOY_WEBHOOK_URL

workflows:
  pipeline:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: develop
