version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: cd scripts && yarn
      - run: node scripts/deploy.js $RENDER_DEPLOY_URL_STAGING

workflows:
  pipeline:
    jobs:
      # - test
      - deploy
