version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  unit-testing: 
    docker:       
      - image: circleci/node      
    steps:
      - checkout
      - run: yarn
      - run: yarn test

workflows:
  testing:
    jobs:
      - unit-testing:
        filters: 
          branches:
            only: /*/