version: 2.1
orbs:
  node: circleci/node@5.1.0
commands:
  install-pnpm:
    steps:
      - run: npm install -g pnpm@7.25.1
  checkout-and-install:
    steps:
      - checkout
      - install-pnpm
      - run: pnpm install --frozen-lockfile

jobs:
  test:
    docker:
      - image: cimg/node:16.18.1
    steps:
      - checkout-and-install
      - run: pnpm run test --runInBand
  build:
    docker:
      - image: cimg/node:16.18.1
    steps:
      - checkout-and-install
      - run: pnpm build
  stage:
    docker:
      - image: cimg/node:16.18.1
    steps:
      - checkout-and-install
      - run: pnpm run deploy $DEPLOY_WEBHOOK_URL_STAGING
  deploy:
    docker:
      - image: cimg/node:16.18.1
    steps:
      - checkout-and-install
      - run: pnpm run deploy $DEPLOY_WEBHOOK_URL

workflows:
  pipeline:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: develop
      - stage:
          requires:
            - test
            - build
          filters:
            branches:
              only: develop
