version: 2.1
orbs:
  node: circleci/node@5.0.3

jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn
      - run: yarn test
      - run: mkdir test_results
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: node scripts/deploy.js

workflows:
  pipeline:
    jobs:
      - test
      - deploy:
          requires:
            - test
