version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@0.0.10

jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn
      - run: yarn test
  stage:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: $HEROKU_STAGING_APP_NAME
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  testing:
    jobs:
      - test:
        filters:
          branches:
            only: /*/
  deploy:
    jobs:
      - test
      - stage:
          requires:
            - test
          filters:
            branches:
              only: develop
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: develop
